{% set name = "dist-meta" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fa16ebd5574744a09596ab342083a11d7209d8d05cf32891d1c985be7ec0cbd7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatchling
    - hatch-requirements-txt
    - pip
    - python {{ python_min }}
  run:
    - domdf-python-tools >=3.1.0
    - handy-archives >=0.1.0
    - packaging >=20.9
    - python >={{ python_min }}

test:
  imports:
    - dist_meta
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/repo-helper/dist-meta
  summary: Parse and create Python distribution metadata.
  license: MIT
  license_file: LICENSE
  doc_url: https://dist-meta.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - domdfcoding
