{% set name = "dist-meta" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dist-meta-{{ version }}.tar.gz
  sha256: 2be2ac8a925d56be1a68ff0bc5d339d44693b43906929a77b8aa3200d0238f5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - domdf-python-tools >=3.1.0
    - handy-archives >=0.1.0
    - packaging >=20.9
    - python >=3.6

test:
  imports:
    - dist_meta
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/repo-helper/dist-meta
  summary: Parse and create Python distribution metadata.
  license: MIT
  license_file: LICENSE
  doc_url: https://dist-meta.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - domdfcoding
