{% set name = "dist-meta" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dist-meta-{{ version }}.tar.gz
  sha256: e73b873b08361835e25592d4d74129f0353bca4451dd12bfa10aaf14af4682e4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - domdf-python-tools >=3.1.0
    - handy-archives >=0.1.0
    - packaging >=20.9
    - python >={{ python_min }}

test:
  imports:
    - dist_meta
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/repo-helper/dist-meta
  summary: Parse and create Python distribution metadata.
  license: MIT
  license_file: LICENSE
  doc_url: https://dist-meta.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - domdfcoding
